export * from './desktop-world-client.js';
export * from './desktop-world-session.js';
export * from './scene-result-codes.js';
export * from './scene-interaction-visual.js';
export {
  DesktopWorldSurface3D,
  DesktopWorldSurfaceThree,
  deriveOrthoCamera,
  canvasGeometryCanvasID,
  canvasLifecycleCanvasID,
  mergeCanvasGeometryCanvas,
  mergeCanvasLifecycleCanvas,
  normalizeCanvasGeometry,
  DEFAULT_THREE_RENDER_LIMITS,
  createThreeRenderLifecycle,
  disposeThreeObjectTree,
  disposeThreeRenderer,
  resolveThreeRenderMetrics,
  DEFAULT_SCENE_HOST_BUDGETS,
  SCENE_INSPECTION_CONTRACT_ID,
  createDesktopWorldSceneHost,
  createLocalSceneViewportHost,
  GENERIC_SCENE_IMPLEMENTATIONS,
  createGenericSceneImplementationRegistry,
  createGenericThreeSceneProjection,
  SCENE_ANIMATION_BINDING_IMPLEMENTATION_ID,
  compileSceneAnimationBindings,
  createSceneAnimationController,
  SCENE_SIGNAL_BINDING_IMPLEMENTATION_ID,
  compileSceneSignalBindings,
  createSceneSignalController,
} from './index.js';
export type {
  CanvasGeometryProjection,
  CanvasLifecycleProjection,
  DesktopWorldSegment,
  DisposableResource,
  OrthoCameraProjection,
  SceneAnimationBinding,
  SceneAnimationController,
  SceneHost,
  SceneHostBudgets,
  SceneHostOptions,
  SceneHostResult,
  SceneHostSnapshot,
  SceneHostStatus,
  SceneInspection,
  SceneProjection,
  SceneProjectionContext,
  SceneSignalBinding,
  SceneSignalController,
  ThreeCameraLike,
  ThreeObjectDisposalSummary,
  ThreeRenderDisposalSummary,
  ThreeRendererDisposalSummary,
  ThreeRendererLike,
  ThreeRenderFrame,
  ThreeRenderLifecycle,
  ThreeRenderLifecycleOptions,
  ThreeRenderLifecycleSnapshot,
  ThreeRenderLimits,
  ThreeRenderMetrics,
} from './index.js';
