#!/bin/bash
# launch.sh - Create a local-only Decision Gate smoke prompt.

set -euo pipefail

DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(git -C "$DIR" rev-parse --show-toplevel 2>/dev/null || pwd)"
source "$ROOT/scripts/aos-content-scope.sh"

AOS="${AOS:-$ROOT/aos}"
CANVAS_ID="${AOS_DECISION_GATE_ID:-decision-gate-live-sweep}"
PANEL_W="${AOS_DECISION_GATE_W:-760}"
PANEL_H="${AOS_DECISION_GATE_H:-460}"
TOOLKIT_CONTENT_ROOT="${AOS_TOOLKIT_CONTENT_ROOT:-$(aos_content_root_key_for toolkit "$ROOT")}"

"$AOS" show remove --id "$CANVAS_ID" 2>/dev/null || true

aos_ensure_content_roots_live "$AOS" \
  "$TOOLKIT_CONTENT_ROOT" "$ROOT/packages/toolkit"

REQUEST_B64="$(node - <<'NODE'
const request = {
  prompt: {
    title: 'Local smoke decision',
    body: 'This request is generated by the toolkit Decision Gate launch helper and has no external side effects.',
  },
  fields: [
    {
      id: 'decision',
      kind: 'exclusive_choice',
      label: 'Decision',
      options: [
        { value: 'continue', label: 'Continue' },
        { value: 'block', label: 'Block' },
      ],
    },
    {
      id: 'note',
      kind: 'text',
      label: 'Note',
      optional: true,
      placeholder: 'Optional local note',
    },
  ],
  ui: {
    submit_label: 'Submit local result',
    timer: { visible: true, display: 'digital', direction: 'down' },
  },
  timeout_ms: 60000,
}
process.stdout.write(Buffer.from(JSON.stringify(request), 'utf8').toString('base64url'))
NODE
)"

"$AOS" show create --id "$CANVAS_ID" \
  --at "160,120,$PANEL_W,$PANEL_H" \
  --interactive \
  --focus \
  --scope global \
  --url "aos://$TOOLKIT_CONTENT_ROOT/components/decision-gate/index.html?requestB64=$REQUEST_B64"

"$AOS" show wait \
  --id "$CANVAS_ID" \
  --manifest decision-gate \
  --js '!!document.querySelector(".aos-gate-submit") && document.body.innerText.includes("Local smoke decision")' \
  --timeout 5s \
  --json >/dev/null

echo "Decision Gate local smoke prompt launched as ${CANVAS_ID}"
