// Generated by scripts/employer-brand-report-data.mjs. Do not edit by hand.
// Source fixture: docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/

const templateMeta = {
  "reportTitle": "Employer Brand Comparative Audit Fixture",
  "reportSubtitle": "Symphony Talent with Phenom and Radancy | Local fixture data",
  "footerText": "(c) 2026 AOS local fixture. No live-web collection or export execution.",
  "headerLogo": "./assets/branding/symphony-talent-header.png",
  "heroLogo": "./assets/branding/symphony-talent-hero.png",
  "overviewBackground": "./assets/backgrounds/overview-bg.jpg",
  "contentBackground": "./assets/backgrounds/content-bg.jpg",
  "watermarkGraphic": "",
  "generatedFrom": "docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit",
  "generatedBy": "scripts/employer-brand-report-data.mjs"
};

const client = {
  "companyName": "Symphony Talent",
  "companyRole": "client",
  "companyLogo": {
    "localPath": "./assets/branding/symphony-talent-header.png",
    "description": "Symphony Talent report header logo",
    "sourceURL": "https://www.symphonytalent.com/"
  },
  "companyEvidence": {
    "local fixture careers page": {
      "sourceDomain": "Local fixture careers page",
      "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/symphony-talent-careers.html",
      "sourceURLs": [
        "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/symphony-talent-careers.html",
        "https://www.symphonytalent.com/"
      ],
      "publicSourceURL": "https://www.symphonytalent.com/",
      "requestIDs": [
        "symphony_talent_careers_site_planning"
      ],
      "caveats": [
        "This company audit cites only one local Browser Evidence registry row.",
        "The fixture is not a live-web capture and does not support market-current claims.",
        "Review-site coverage is unavailable in this slice.",
        "Review platforms are required in the full workflow but are outside this first local fixture slice."
      ],
      "images": [
        {
          "localPath": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/screenshots/symphony-talent/symphony-talent-fixture-evp-hero.png",
          "description": "capture the local fixture hero used as the client employer value proposition evidence sample",
          "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/symphony-talent-careers.html",
          "publicSourceURL": "https://www.symphonytalent.com/",
          "requestID": "symphony_talent_careers_site_planning",
          "requestIDs": [
            "symphony_talent_careers_site_planning"
          ],
          "selector": "[data-evidence-id='symphony-hero']",
          "capturedAt": "2026-05-07T15:11:01Z",
          "caveat": "Fixture page only; not collected from the live Symphony Talent website.",
          "extractedText": "SYMPHONY TALENT FIXTURE Build talent experiences with people who care about craft and impact. Teams connect creative storytelling, recruitment marketing technology, and client partnership to help employers reach candidates with more relevant experiences."
        }
      ],
      "textualEvidence": [
        {
          "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/symphony-talent-careers.html",
          "publicSourceURL": "https://www.symphonytalent.com/",
          "requestID": "symphony_talent_careers_site_planning",
          "requestIDs": [
            "symphony_talent_careers_site_planning"
          ],
          "type": "browser_evidence_excerpt",
          "context": "capture the local fixture hero used as the client employer value proposition evidence sample",
          "caveat": "Fixture page only; not collected from the live Symphony Talent website.",
          "content": {
            "text": "SYMPHONY TALENT FIXTURE Build talent experiences with people who care about craft and impact. Teams connect creative storytelling, recruitment marketing technology, and client partnership to help employers reach candidates with more relevant experiences."
          }
        }
      ]
    }
  },
  "sourceMetadata": {
    "sourceID": "source:symphony-talent-homepage",
    "publicSourceURL": "https://www.symphonytalent.com/",
    "collectionStatus": "not_collected_in_fixture",
    "fixtureSignal": "Opportunity",
    "notes": "Static source reference carried for provenance only. A production audit should attach browser text, screenshots, and timestamped collection evidence."
  },
  "requestIDs": [
    "symphony_talent_careers_site_planning"
  ],
  "caveats": [
    "This company audit cites only one local Browser Evidence registry row.",
    "The fixture is not a live-web capture and does not support market-current claims.",
    "Review-site coverage is unavailable in this slice.",
    "Review platforms are required in the full workflow but are outside this first local fixture slice."
  ],
  "analysis": {
    "scientificTalentValueProposition": {
      "primaryHeadline": {
        "text": "People who care about craft can help employers reach candidates with more relevant talent experiences.",
        "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/symphony-talent-careers.html",
        "sourceURLs": [
          "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/symphony-talent-careers.html",
          "https://www.symphonytalent.com/"
        ],
        "requestIDs": [
          "symphony_talent_careers_site_planning"
        ],
        "caveats": [
          "This company audit cites only one local Browser Evidence registry row.",
          "The fixture is not a live-web capture and does not support market-current claims.",
          "Review-site coverage is unavailable in this slice.",
          "Review platforms are required in the full workflow but are outside this first local fixture slice."
        ]
      },
      "keyPillarStatements": [
        {
          "statement": "Craft and client impact: The main evidence sample blends creative storytelling, technology, and client partnership into one employer promise.",
          "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/symphony-talent-careers.html",
          "sourceURLs": [
            "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/symphony-talent-careers.html",
            "https://www.symphonytalent.com/"
          ],
          "requestIDs": [
            "symphony_talent_careers_site_planning"
          ],
          "caveats": [
            "This company audit cites only one local Browser Evidence registry row.",
            "The fixture is not a live-web capture and does not support market-current claims.",
            "Review-site coverage is unavailable in this slice.",
            "Review platforms are required in the full workflow but are outside this first local fixture slice."
          ]
        },
        {
          "statement": "The strongest differentiator in the fixture is the combination of creative storytelling, recruitment marketing technology, and client partnership.",
          "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/symphony-talent-careers.html",
          "sourceURLs": [
            "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/symphony-talent-careers.html",
            "https://www.symphonytalent.com/"
          ],
          "requestIDs": [
            "symphony_talent_careers_site_planning"
          ],
          "caveats": [
            "This company audit cites only one local Browser Evidence registry row.",
            "The fixture is not a live-web capture and does not support market-current claims.",
            "Review-site coverage is unavailable in this slice.",
            "Review platforms are required in the full workflow but are outside this first local fixture slice."
          ]
        }
      ],
      "summary": "Symphony Talent is framed as a place to build talent experiences through craft, impact, and client partnership.",
      "sourceURLs": [
        "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/symphony-talent-careers.html",
        "https://www.symphonytalent.com/"
      ],
      "requestIDs": [
        "symphony_talent_careers_site_planning"
      ],
      "caveats": [
        "This company audit cites only one local Browser Evidence registry row.",
        "The fixture is not a live-web capture and does not support market-current claims.",
        "Review-site coverage is unavailable in this slice.",
        "Review platforms are required in the full workflow but are outside this first local fixture slice."
      ]
    },
    "kilosFrameworkAnalysis": {
      "Impact": {
        "presence": true,
        "summary": "The fixture copy connects employee work to helping employers reach candidates with more relevant experiences.",
        "sourceURLs": [
          "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/symphony-talent-careers.html",
          "https://www.symphonytalent.com/"
        ],
        "requestIDs": [
          "symphony_talent_careers_site_planning"
        ],
        "caveats": [
          "This company audit cites only one local Browser Evidence registry row.",
          "The fixture is not a live-web capture and does not support market-current claims.",
          "Review-site coverage is unavailable in this slice.",
          "Review platforms are required in the full workflow but are outside this first local fixture slice."
        ],
        "supportingEvidence": [
          {
            "evidenceText": "The fixture copy connects employee work to helping employers reach candidates with more relevant experiences.",
            "theme": "meaningful work for people",
            "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/symphony-talent-careers.html",
            "sourceURLs": [
              "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/symphony-talent-careers.html",
              "https://www.symphonytalent.com/"
            ],
            "requestIDs": [
              "symphony_talent_careers_site_planning"
            ],
            "caveat": "Fixture page only; not collected from the live Symphony Talent website."
          },
          {
            "evidenceText": "Symphony Talent's local fixture positions its employer promise around craft, impact, technology, and client partnership.",
            "theme": "claim:symphony-talent-craft-impact-promise",
            "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/symphony-talent-careers.html",
            "sourceURLs": [
              "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/symphony-talent-careers.html",
              "https://www.symphonytalent.com/"
            ],
            "requestIDs": [
              "symphony_talent_careers_site_planning"
            ],
            "caveat": "Fixture claim derived from local company audit JSON."
          }
        ]
      },
      "Opportunity": {
        "presence": true,
        "summary": "The message emphasizes craft, recruitment marketing technology, and client partnership as professional expertise signals.",
        "sourceURLs": [
          "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/symphony-talent-careers.html",
          "https://www.symphonytalent.com/"
        ],
        "requestIDs": [
          "symphony_talent_careers_site_planning"
        ],
        "caveats": [
          "This company audit cites only one local Browser Evidence registry row.",
          "The fixture is not a live-web capture and does not support market-current claims.",
          "Review-site coverage is unavailable in this slice.",
          "Review platforms are required in the full workflow but are outside this first local fixture slice."
        ],
        "supportingEvidence": [
          {
            "evidenceText": "The message emphasizes craft, recruitment marketing technology, and client partnership as professional expertise signals.",
            "theme": "professional expertise",
            "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/symphony-talent-careers.html",
            "sourceURLs": [
              "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/symphony-talent-careers.html",
              "https://www.symphonytalent.com/"
            ],
            "requestIDs": [
              "symphony_talent_careers_site_planning"
            ],
            "caveat": "Fixture page only; not collected from the live Symphony Talent website."
          },
          {
            "evidenceText": "Symphony Talent's local fixture positions its employer promise around craft, impact, technology, and client partnership.",
            "theme": "claim:symphony-talent-craft-impact-promise",
            "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/symphony-talent-careers.html",
            "sourceURLs": [
              "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/symphony-talent-careers.html",
              "https://www.symphonytalent.com/"
            ],
            "requestIDs": [
              "symphony_talent_careers_site_planning"
            ],
            "caveat": "Fixture claim derived from local company audit JSON."
          }
        ]
      }
    },
    "brandVoiceAndTone": {
      "summary": "The tone is confident, collaborative, and craft-oriented.",
      "descriptors": [
        "craft-led",
        "collaborative",
        "impact-oriented"
      ],
      "request_ids": [
        "symphony_talent_careers_site_planning"
      ]
    },
    "evidenceBackedClaims": [
      {
        "id": "claim:symphony-talent-craft-impact-promise",
        "claim": "Symphony Talent's local fixture positions its employer promise around craft, impact, technology, and client partnership.",
        "request_ids": [
          "symphony_talent_careers_site_planning"
        ]
      }
    ],
    "genericMessagingOrWeakSpots": [
      {
        "summary": "The hero-level fixture does not yet prove employee stories, benefits, review sentiment, or concrete career mobility claims.",
        "request_ids": [
          "symphony_talent_careers_site_planning"
        ]
      }
    ]
  }
};

const competitors = [
  {
    "companyName": "Phenom",
    "companyRole": "competitor",
    "companyLogo": {
      "description": "No local Phenom logo asset is included in this fixture slice; the static report shell renders a name fallback.",
      "sourceURL": "https://www.phenom.com/",
      "caveat": "No local company logo asset is included in this fixture slice."
    },
    "companyEvidence": {
      "local fixture careers page": {
        "sourceDomain": "Local fixture careers page",
        "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/phenom-careers.html",
        "sourceURLs": [
          "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/phenom-careers.html",
          "https://www.phenom.com/"
        ],
        "publicSourceURL": "https://www.phenom.com/",
        "requestIDs": [
          "phenom_careers_site_planning"
        ],
        "caveats": [
          "This company audit cites only one local Browser Evidence registry row.",
          "The fixture is not a live-web capture and does not support market-current claims.",
          "Review-site coverage is unavailable in this slice.",
          "Review platforms are required in the full workflow but are outside this first local fixture slice."
        ],
        "images": [
          {
            "localPath": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/screenshots/phenom/phenom-fixture-culture-card.png",
            "description": "capture the local fixture culture card used as competitor employer brand evidence",
            "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/phenom-careers.html",
            "publicSourceURL": "https://www.phenom.com/",
            "requestID": "phenom_careers_site_planning",
            "requestIDs": [
              "phenom_careers_site_planning"
            ],
            "selector": "[data-evidence-id='phenom-culture']",
            "capturedAt": "2026-05-07T15:11:02Z",
            "caveat": "Fixture page only; not collected from the live Phenom website.",
            "extractedText": "Make every talent moment more personal. Employees are shown as builders of intelligent experiences, with emphasis on product pace, customer outcomes, and collaborative problem solving across teams."
          }
        ],
        "textualEvidence": [
          {
            "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/phenom-careers.html",
            "publicSourceURL": "https://www.phenom.com/",
            "requestID": "phenom_careers_site_planning",
            "requestIDs": [
              "phenom_careers_site_planning"
            ],
            "type": "browser_evidence_excerpt",
            "context": "capture the local fixture culture card used as competitor employer brand evidence",
            "caveat": "Fixture page only; not collected from the live Phenom website.",
            "content": {
              "text": "Make every talent moment more personal. Employees are shown as builders of intelligent experiences, with emphasis on product pace, customer outcomes, and collaborative problem solving across teams."
            }
          }
        ]
      }
    },
    "sourceMetadata": {
      "sourceID": "source:phenom-homepage",
      "publicSourceURL": "https://www.phenom.com/",
      "collectionStatus": "not_collected_in_fixture",
      "fixtureSignal": "Impact",
      "notes": "Static source reference carried for provenance only. A production audit should attach browser text, screenshots, and timestamped collection evidence."
    },
    "requestIDs": [
      "phenom_careers_site_planning"
    ],
    "caveats": [
      "This company audit cites only one local Browser Evidence registry row.",
      "The fixture is not a live-web capture and does not support market-current claims.",
      "Review-site coverage is unavailable in this slice.",
      "Review platforms are required in the full workflow but are outside this first local fixture slice."
    ],
    "analysis": {
      "scientificTalentValueProposition": {
        "primaryHeadline": {
          "text": "Employees can make every talent moment more personal through product building, customer outcomes, and collaborative problem solving.",
          "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/phenom-careers.html",
          "sourceURLs": [
            "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/phenom-careers.html",
            "https://www.phenom.com/"
          ],
          "requestIDs": [
            "phenom_careers_site_planning"
          ],
          "caveats": [
            "This company audit cites only one local Browser Evidence registry row.",
            "The fixture is not a live-web capture and does not support market-current claims.",
            "Review-site coverage is unavailable in this slice.",
            "Review platforms are required in the full workflow but are outside this first local fixture slice."
          ]
        },
        "keyPillarStatements": [
          {
            "statement": "Personalized talent moments: The fixture makes personalization the core promise and ties it to employee product work.",
            "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/phenom-careers.html",
            "sourceURLs": [
              "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/phenom-careers.html",
              "https://www.phenom.com/"
            ],
            "requestIDs": [
              "phenom_careers_site_planning"
            ],
            "caveats": [
              "This company audit cites only one local Browser Evidence registry row.",
              "The fixture is not a live-web capture and does not support market-current claims.",
              "Review-site coverage is unavailable in this slice.",
              "Review platforms are required in the full workflow but are outside this first local fixture slice."
            ]
          },
          {
            "statement": "Builder culture: Employees are described as builders of intelligent experiences rather than only operators of a platform.",
            "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/phenom-careers.html",
            "sourceURLs": [
              "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/phenom-careers.html",
              "https://www.phenom.com/"
            ],
            "requestIDs": [
              "phenom_careers_site_planning"
            ],
            "caveats": [
              "This company audit cites only one local Browser Evidence registry row.",
              "The fixture is not a live-web capture and does not support market-current claims.",
              "Review-site coverage is unavailable in this slice.",
              "Review platforms are required in the full workflow but are outside this first local fixture slice."
            ]
          },
          {
            "statement": "The strongest differentiator in the fixture is the link between personalization, intelligent experiences, product pace, and customer outcomes.",
            "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/phenom-careers.html",
            "sourceURLs": [
              "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/phenom-careers.html",
              "https://www.phenom.com/"
            ],
            "requestIDs": [
              "phenom_careers_site_planning"
            ],
            "caveats": [
              "This company audit cites only one local Browser Evidence registry row.",
              "The fixture is not a live-web capture and does not support market-current claims.",
              "Review-site coverage is unavailable in this slice.",
              "Review platforms are required in the full workflow but are outside this first local fixture slice."
            ]
          }
        ],
        "summary": "Phenom is framed as a place where employees build intelligent, personal talent experiences at product speed.",
        "sourceURLs": [
          "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/phenom-careers.html",
          "https://www.phenom.com/"
        ],
        "requestIDs": [
          "phenom_careers_site_planning"
        ],
        "caveats": [
          "This company audit cites only one local Browser Evidence registry row.",
          "The fixture is not a live-web capture and does not support market-current claims.",
          "Review-site coverage is unavailable in this slice.",
          "Review platforms are required in the full workflow but are outside this first local fixture slice."
        ]
      },
      "kilosFrameworkAnalysis": {
        "Impact": {
          "presence": true,
          "summary": "The fixture centers intelligent experiences, product pace, and customer outcomes as the employee impact story.",
          "sourceURLs": [
            "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/phenom-careers.html",
            "https://www.phenom.com/"
          ],
          "requestIDs": [
            "phenom_careers_site_planning"
          ],
          "caveats": [
            "This company audit cites only one local Browser Evidence registry row.",
            "The fixture is not a live-web capture and does not support market-current claims.",
            "Review-site coverage is unavailable in this slice.",
            "Review platforms are required in the full workflow but are outside this first local fixture slice."
          ],
          "supportingEvidence": [
            {
              "evidenceText": "The fixture centers intelligent experiences, product pace, and customer outcomes as the employee impact story.",
              "theme": "innovation and invention",
              "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/phenom-careers.html",
              "sourceURLs": [
                "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/phenom-careers.html",
                "https://www.phenom.com/"
              ],
              "requestIDs": [
                "phenom_careers_site_planning"
              ],
              "caveat": "Fixture page only; not collected from the live Phenom website."
            },
            {
              "evidenceText": "Phenom's local fixture positions employees as builders of intelligent, personalized talent experiences.",
              "theme": "claim:phenom-personalized-builder-culture",
              "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/phenom-careers.html",
              "sourceURLs": [
                "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/phenom-careers.html",
                "https://www.phenom.com/"
              ],
              "requestIDs": [
                "phenom_careers_site_planning"
              ],
              "caveat": "Fixture claim derived from local company audit JSON."
            }
          ]
        },
        "Kinship": {
          "presence": true,
          "summary": "The copy points to collaborative problem solving across teams, which is the clearest available kinship signal in the local evidence.",
          "sourceURLs": [
            "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/phenom-careers.html",
            "https://www.phenom.com/"
          ],
          "requestIDs": [
            "phenom_careers_site_planning"
          ],
          "caveats": [
            "This company audit cites only one local Browser Evidence registry row.",
            "The fixture is not a live-web capture and does not support market-current claims.",
            "Review-site coverage is unavailable in this slice.",
            "Review platforms are required in the full workflow but are outside this first local fixture slice."
          ],
          "supportingEvidence": [
            {
              "evidenceText": "The copy points to collaborative problem solving across teams, which is the clearest available kinship signal in the local evidence.",
              "theme": "sense of belonging",
              "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/phenom-careers.html",
              "sourceURLs": [
                "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/phenom-careers.html",
                "https://www.phenom.com/"
              ],
              "requestIDs": [
                "phenom_careers_site_planning"
              ],
              "caveat": "Fixture page only; not collected from the live Phenom website."
            },
            {
              "evidenceText": "Phenom's local fixture positions employees as builders of intelligent, personalized talent experiences.",
              "theme": "claim:phenom-personalized-builder-culture",
              "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/phenom-careers.html",
              "sourceURLs": [
                "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/phenom-careers.html",
                "https://www.phenom.com/"
              ],
              "requestIDs": [
                "phenom_careers_site_planning"
              ],
              "caveat": "Fixture claim derived from local company audit JSON."
            }
          ]
        }
      },
      "brandVoiceAndTone": {
        "summary": "The tone is energetic, product-led, and customer-outcome oriented.",
        "descriptors": [
          "product-led",
          "energetic",
          "customer-focused"
        ],
        "request_ids": [
          "phenom_careers_site_planning"
        ]
      },
      "evidenceBackedClaims": [
        {
          "id": "claim:phenom-personalized-builder-culture",
          "claim": "Phenom's local fixture positions employees as builders of intelligent, personalized talent experiences.",
          "request_ids": [
            "phenom_careers_site_planning"
          ]
        }
      ],
      "genericMessagingOrWeakSpots": [
        {
          "summary": "The fixture does not yet provide proof of benefits, career paths, leadership access, or review sentiment.",
          "request_ids": [
            "phenom_careers_site_planning"
          ]
        }
      ]
    }
  },
  {
    "companyName": "Radancy",
    "companyRole": "competitor",
    "companyLogo": {
      "description": "No local Radancy logo asset is included in this fixture slice; the static report shell renders a name fallback.",
      "sourceURL": "https://www.radancy.com/en/",
      "caveat": "No local company logo asset is included in this fixture slice."
    },
    "companyEvidence": {
      "local fixture careers page": {
        "sourceDomain": "Local fixture careers page",
        "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/radancy-careers.html",
        "sourceURLs": [
          "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/radancy-careers.html",
          "https://www.radancy.com/en/"
        ],
        "publicSourceURL": "https://www.radancy.com/en/",
        "requestIDs": [
          "radancy_careers_site_planning"
        ],
        "caveats": [
          "This company audit cites only one local Browser Evidence registry row.",
          "The fixture is not a live-web capture and does not support market-current claims.",
          "Review-site coverage is unavailable in this slice.",
          "Review platforms are required in the full workflow but are outside this first local fixture slice."
        ],
        "images": [
          {
            "localPath": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/screenshots/radancy/radancy-fixture-proof-block.png",
            "description": "capture the local fixture proof block used as competitor status evidence",
            "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/radancy-careers.html",
            "publicSourceURL": "https://www.radancy.com/en/",
            "requestID": "radancy_careers_site_planning",
            "requestIDs": [
              "radancy_careers_site_planning"
            ],
            "selector": "[data-evidence-id='radancy-proof']",
            "capturedAt": "2026-05-07T15:11:03Z",
            "caveat": "Fixture page only; not collected from the live Radancy website.",
            "extractedText": "Work on enterprise hiring programs with global reach. The fixture emphasizes scale, established client programs, and specialist recruitment marketing expertise as employer brand proof points."
          }
        ],
        "textualEvidence": [
          {
            "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/radancy-careers.html",
            "publicSourceURL": "https://www.radancy.com/en/",
            "requestID": "radancy_careers_site_planning",
            "requestIDs": [
              "radancy_careers_site_planning"
            ],
            "type": "browser_evidence_excerpt",
            "context": "capture the local fixture proof block used as competitor status evidence",
            "caveat": "Fixture page only; not collected from the live Radancy website.",
            "content": {
              "text": "Work on enterprise hiring programs with global reach. The fixture emphasizes scale, established client programs, and specialist recruitment marketing expertise as employer brand proof points."
            }
          }
        ]
      }
    },
    "sourceMetadata": {
      "sourceID": "source:radancy-homepage",
      "publicSourceURL": "https://www.radancy.com/en/",
      "collectionStatus": "not_collected_in_fixture",
      "fixtureSignal": "Status",
      "notes": "Static source reference carried for provenance only. A production audit should attach browser text, screenshots, and timestamped collection evidence."
    },
    "requestIDs": [
      "radancy_careers_site_planning"
    ],
    "caveats": [
      "This company audit cites only one local Browser Evidence registry row.",
      "The fixture is not a live-web capture and does not support market-current claims.",
      "Review-site coverage is unavailable in this slice.",
      "Review platforms are required in the full workflow but are outside this first local fixture slice."
    ],
    "analysis": {
      "scientificTalentValueProposition": {
        "primaryHeadline": {
          "text": "Employees can apply specialist expertise to established, scaled hiring programs.",
          "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/radancy-careers.html",
          "sourceURLs": [
            "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/radancy-careers.html",
            "https://www.radancy.com/en/"
          ],
          "requestIDs": [
            "radancy_careers_site_planning"
          ],
          "caveats": [
            "This company audit cites only one local Browser Evidence registry row.",
            "The fixture is not a live-web capture and does not support market-current claims.",
            "Review-site coverage is unavailable in this slice.",
            "Review platforms are required in the full workflow but are outside this first local fixture slice."
          ]
        },
        "keyPillarStatements": [
          {
            "statement": "Scaled enterprise hiring: The fixture presents global reach and enterprise programs as proof that employee work operates at scale.",
            "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/radancy-careers.html",
            "sourceURLs": [
              "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/radancy-careers.html",
              "https://www.radancy.com/en/"
            ],
            "requestIDs": [
              "radancy_careers_site_planning"
            ],
            "caveats": [
              "This company audit cites only one local Browser Evidence registry row.",
              "The fixture is not a live-web capture and does not support market-current claims.",
              "Review-site coverage is unavailable in this slice.",
              "Review platforms are required in the full workflow but are outside this first local fixture slice."
            ]
          },
          {
            "statement": "Specialist expertise: The proof block leans on recruitment marketing specialization as an employer-brand asset.",
            "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/radancy-careers.html",
            "sourceURLs": [
              "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/radancy-careers.html",
              "https://www.radancy.com/en/"
            ],
            "requestIDs": [
              "radancy_careers_site_planning"
            ],
            "caveats": [
              "This company audit cites only one local Browser Evidence registry row.",
              "The fixture is not a live-web capture and does not support market-current claims.",
              "Review-site coverage is unavailable in this slice.",
              "Review platforms are required in the full workflow but are outside this first local fixture slice."
            ]
          },
          {
            "statement": "The strongest differentiator in the fixture is the status signal from global reach, established client programs, and specialist hiring expertise.",
            "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/radancy-careers.html",
            "sourceURLs": [
              "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/radancy-careers.html",
              "https://www.radancy.com/en/"
            ],
            "requestIDs": [
              "radancy_careers_site_planning"
            ],
            "caveats": [
              "This company audit cites only one local Browser Evidence registry row.",
              "The fixture is not a live-web capture and does not support market-current claims.",
              "Review-site coverage is unavailable in this slice.",
              "Review platforms are required in the full workflow but are outside this first local fixture slice."
            ]
          }
        ],
        "summary": "Radancy is framed as a place to work on enterprise hiring programs with global reach and specialist recruitment marketing expertise.",
        "sourceURLs": [
          "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/radancy-careers.html",
          "https://www.radancy.com/en/"
        ],
        "requestIDs": [
          "radancy_careers_site_planning"
        ],
        "caveats": [
          "This company audit cites only one local Browser Evidence registry row.",
          "The fixture is not a live-web capture and does not support market-current claims.",
          "Review-site coverage is unavailable in this slice.",
          "Review platforms are required in the full workflow but are outside this first local fixture slice."
        ]
      },
      "kilosFrameworkAnalysis": {
        "Status": {
          "presence": true,
          "summary": "The fixture emphasizes enterprise programs, global reach, scale, and established client work as reputation proof points.",
          "sourceURLs": [
            "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/radancy-careers.html",
            "https://www.radancy.com/en/"
          ],
          "requestIDs": [
            "radancy_careers_site_planning"
          ],
          "caveats": [
            "This company audit cites only one local Browser Evidence registry row.",
            "The fixture is not a live-web capture and does not support market-current claims.",
            "Review-site coverage is unavailable in this slice.",
            "Review platforms are required in the full workflow but are outside this first local fixture slice."
          ],
          "supportingEvidence": [
            {
              "evidenceText": "The fixture emphasizes enterprise programs, global reach, scale, and established client work as reputation proof points.",
              "theme": "industry reputation",
              "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/radancy-careers.html",
              "sourceURLs": [
                "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/radancy-careers.html",
                "https://www.radancy.com/en/"
              ],
              "requestIDs": [
                "radancy_careers_site_planning"
              ],
              "caveat": "Fixture page only; not collected from the live Radancy website."
            },
            {
              "evidenceText": "Radancy's local fixture positions enterprise scale, global reach, and recruitment marketing expertise as employer-brand proof points.",
              "theme": "claim:radancy-enterprise-scale-proof",
              "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/radancy-careers.html",
              "sourceURLs": [
                "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/radancy-careers.html",
                "https://www.radancy.com/en/"
              ],
              "requestIDs": [
                "radancy_careers_site_planning"
              ],
              "caveat": "Fixture claim derived from local company audit JSON."
            }
          ]
        },
        "Opportunity": {
          "presence": true,
          "summary": "Specialist recruitment marketing expertise is the clearest development and professional mastery signal in the available evidence.",
          "sourceURLs": [
            "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/radancy-careers.html",
            "https://www.radancy.com/en/"
          ],
          "requestIDs": [
            "radancy_careers_site_planning"
          ],
          "caveats": [
            "This company audit cites only one local Browser Evidence registry row.",
            "The fixture is not a live-web capture and does not support market-current claims.",
            "Review-site coverage is unavailable in this slice.",
            "Review platforms are required in the full workflow but are outside this first local fixture slice."
          ],
          "supportingEvidence": [
            {
              "evidenceText": "Specialist recruitment marketing expertise is the clearest development and professional mastery signal in the available evidence.",
              "theme": "professional expertise",
              "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/radancy-careers.html",
              "sourceURLs": [
                "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/radancy-careers.html",
                "https://www.radancy.com/en/"
              ],
              "requestIDs": [
                "radancy_careers_site_planning"
              ],
              "caveat": "Fixture page only; not collected from the live Radancy website."
            },
            {
              "evidenceText": "Radancy's local fixture positions enterprise scale, global reach, and recruitment marketing expertise as employer-brand proof points.",
              "theme": "claim:radancy-enterprise-scale-proof",
              "sourceURL": "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/radancy-careers.html",
              "sourceURLs": [
                "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/radancy-careers.html",
                "https://www.radancy.com/en/"
              ],
              "requestIDs": [
                "radancy_careers_site_planning"
              ],
              "caveat": "Fixture claim derived from local company audit JSON."
            }
          ]
        }
      },
      "brandVoiceAndTone": {
        "summary": "The tone is established, proof-led, and expertise-oriented.",
        "descriptors": [
          "established",
          "proof-led",
          "expertise-oriented"
        ],
        "request_ids": [
          "radancy_careers_site_planning"
        ]
      },
      "evidenceBackedClaims": [
        {
          "id": "claim:radancy-enterprise-scale-proof",
          "claim": "Radancy's local fixture positions enterprise scale, global reach, and recruitment marketing expertise as employer-brand proof points.",
          "request_ids": [
            "radancy_careers_site_planning"
          ]
        }
      ],
      "genericMessagingOrWeakSpots": [
        {
          "summary": "The fixture does not yet provide employee voice, culture specifics, benefits, or review-site sentiment.",
          "request_ids": [
            "radancy_careers_site_planning"
          ]
        }
      ]
    }
  }
];

const comparison = {
  "executiveSummary": {
    "sharedThemes": "Across the local fixture audits, the shared market frame is talent-experience work with different proof centers: Symphony Talent emphasizes craft, impact, technology, and client partnership; Phenom emphasizes intelligent personalization, product pace, customer outcomes, and builder culture; Radancy emphasizes enterprise hiring scale, global reach, established client programs, and specialist recruitment marketing expertise. Talent experience impact: All three fixtures connect employee work to improving hiring or talent experiences, but they differ in whether the proof is framed as craft and relevance, product personalization, or enterprise reach. Professional expertise as the employer promise: Symphony Talent and Radancy explicitly lean on professional craft or specialist expertise, while Phenom translates expertise into product building and intelligent experience creation. Proof gaps in the local slice: The three company audits all record missing review-site, benefits, employee voice, and concrete career mobility evidence, so the comparative read should stay limited to fixture-level positioning rather than market-current claims.",
    "keyDifferentiators": "Symphony Talent: The strongest client differentiator in the local evidence is the combination of creative storytelling, recruitment marketing technology, craft, and client partnership in one employer promise. Phenom: Phenom is differentiated by a product-led personalization story that positions employees as builders of intelligent talent moments tied to customer outcomes. Radancy: Radancy is differentiated by status proof: enterprise hiring programs, global reach, established client work, and specialist recruitment marketing expertise.",
    "whiteSpaceOpportunities": "Own the human relevance layer between creative craft and recruitment technology. Symphony Talent can use future evidence to make its craft-and-impact promise more concrete against Phenom's product-personalization story and Radancy's scale-and-reputation proof. Add proof of employee voice, career growth, benefits, and review sentiment before drawing stronger recommendations. Each source company audit flags unavailable review-site evidence and limited fixture scope, leaving lifestyle, sentiment, and concrete mobility proof underdeveloped across the set.",
    "sourceURLs": [
      "https://www.symphonytalent.com/",
      "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/symphony-talent-careers.html",
      "https://www.phenom.com/",
      "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/phenom-careers.html",
      "https://www.radancy.com/en/",
      "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/radancy-careers.html"
    ],
    "requestIDs": [
      "symphony_talent_careers_site_planning",
      "phenom_careers_site_planning",
      "radancy_careers_site_planning"
    ],
    "caveats": [
      "This comparative audit cites only the three local Company Brand Audit fixtures and their Browser Evidence request IDs.",
      "The fixture is not a live-web comparative audit and does not support market-current claims.",
      "Review-site, benefits, employee story, and career-mobility evidence are unavailable in this slice.",
      "The file is read-only provenance/source metadata, not a generated report or viewer payload.",
      "This company audit cites only one local Browser Evidence registry row.",
      "The fixture is not a live-web capture and does not support market-current claims.",
      "Review-site coverage is unavailable in this slice.",
      "Review platforms are required in the full workflow but are outside this first local fixture slice.",
      "This fixture does not claim the source URLs still contain the sampled positioning. This fixture contains local Browser Evidence Capture V0 pages, registry rows, and crop assets for provenance only; it does not contain live-web captures. This fixture is only evidence for Artifact Bundle preview, provenance, Work Record handoff behavior, and local browser evidence registry inspection."
    ],
    "comparativeAuditID": "comparative-brand-audit:symphony-talent-phenom-radancy"
  },
  "kilosMessagingMatrix": [
    {
      "theme": "Collaborative culture and belonging",
      "dimension": "Kinship",
      "companyScores": {
        "Symphony Talent": "Present",
        "Phenom": "Present",
        "Radancy": "Weak"
      },
      "fixtureImplication": "Culture and belonging signals need more direct source evidence before a polished audit can score them confidently.",
      "sourceURLs": [
        "https://www.symphonytalent.com/",
        "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/symphony-talent-careers.html",
        "https://www.phenom.com/",
        "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/phenom-careers.html",
        "https://www.radancy.com/en/",
        "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/radancy-careers.html"
      ],
      "requestIDs": [
        "symphony_talent_careers_site_planning",
        "phenom_careers_site_planning",
        "radancy_careers_site_planning"
      ],
      "caveats": [
        "This comparative audit cites only the three local Company Brand Audit fixtures and their Browser Evidence request IDs.",
        "The fixture is not a live-web comparative audit and does not support market-current claims.",
        "Review-site, benefits, employee story, and career-mobility evidence are unavailable in this slice.",
        "The file is read-only provenance/source metadata, not a generated report or viewer payload.",
        "This company audit cites only one local Browser Evidence registry row.",
        "The fixture is not a live-web capture and does not support market-current claims.",
        "Review-site coverage is unavailable in this slice.",
        "Review platforms are required in the full workflow but are outside this first local fixture slice.",
        "This fixture does not claim the source URLs still contain the sampled positioning. This fixture contains local Browser Evidence Capture V0 pages, registry rows, and crop assets for provenance only; it does not contain live-web captures. This fixture is only evidence for Artifact Bundle preview, provenance, Work Record handoff behavior, and local browser evidence registry inspection."
      ]
    },
    {
      "theme": "Talent experience impact",
      "dimension": "Impact",
      "companyScores": {
        "Symphony Talent": "Present",
        "Phenom": "Strong",
        "Radancy": "Present"
      },
      "fixtureImplication": "Phenom reads as the clearest impact-led competitor in this static sample.",
      "sourceURLs": [
        "https://www.symphonytalent.com/",
        "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/symphony-talent-careers.html",
        "https://www.phenom.com/",
        "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/phenom-careers.html",
        "https://www.radancy.com/en/",
        "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/radancy-careers.html"
      ],
      "requestIDs": [
        "symphony_talent_careers_site_planning",
        "phenom_careers_site_planning",
        "radancy_careers_site_planning"
      ],
      "caveats": [
        "This comparative audit cites only the three local Company Brand Audit fixtures and their Browser Evidence request IDs.",
        "The fixture is not a live-web comparative audit and does not support market-current claims.",
        "Review-site, benefits, employee story, and career-mobility evidence are unavailable in this slice.",
        "The file is read-only provenance/source metadata, not a generated report or viewer payload.",
        "This company audit cites only one local Browser Evidence registry row.",
        "The fixture is not a live-web capture and does not support market-current claims.",
        "Review-site coverage is unavailable in this slice.",
        "Review platforms are required in the full workflow but are outside this first local fixture slice.",
        "This fixture does not claim the source URLs still contain the sampled positioning. This fixture contains local Browser Evidence Capture V0 pages, registry rows, and crop assets for provenance only; it does not contain live-web captures. This fixture is only evidence for Artifact Bundle preview, provenance, Work Record handoff behavior, and local browser evidence registry inspection."
      ]
    },
    {
      "theme": "Lifestyle evidence gaps",
      "dimension": "Lifestyle",
      "companyScores": {
        "Symphony Talent": "Weak",
        "Phenom": "Present",
        "Radancy": "Weak"
      },
      "fixtureImplication": "Benefits, flexibility, and wellbeing claims are under-evidenced in this fixture and should be collected from careers-specific sources in a real audit.",
      "sourceURLs": [
        "https://www.symphonytalent.com/",
        "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/symphony-talent-careers.html",
        "https://www.phenom.com/",
        "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/phenom-careers.html",
        "https://www.radancy.com/en/",
        "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/radancy-careers.html"
      ],
      "requestIDs": [
        "symphony_talent_careers_site_planning",
        "phenom_careers_site_planning",
        "radancy_careers_site_planning"
      ],
      "caveats": [
        "This comparative audit cites only the three local Company Brand Audit fixtures and their Browser Evidence request IDs.",
        "The fixture is not a live-web comparative audit and does not support market-current claims.",
        "Review-site, benefits, employee story, and career-mobility evidence are unavailable in this slice.",
        "The file is read-only provenance/source metadata, not a generated report or viewer payload.",
        "This company audit cites only one local Browser Evidence registry row.",
        "The fixture is not a live-web capture and does not support market-current claims.",
        "Review-site coverage is unavailable in this slice.",
        "Review platforms are required in the full workflow but are outside this first local fixture slice.",
        "This fixture does not claim the source URLs still contain the sampled positioning. This fixture contains local Browser Evidence Capture V0 pages, registry rows, and crop assets for provenance only; it does not contain live-web captures. This fixture is only evidence for Artifact Bundle preview, provenance, Work Record handoff behavior, and local browser evidence registry inspection."
      ]
    },
    {
      "theme": "Expertise and career opportunity",
      "dimension": "Opportunity",
      "companyScores": {
        "Symphony Talent": "Strong",
        "Phenom": "Present",
        "Radancy": "Present"
      },
      "fixtureImplication": "Symphony Talent has the strongest fixture signal around growth, enablement, and candidate journey improvement.",
      "sourceURLs": [
        "https://www.symphonytalent.com/",
        "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/symphony-talent-careers.html",
        "https://www.phenom.com/",
        "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/phenom-careers.html",
        "https://www.radancy.com/en/",
        "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/radancy-careers.html"
      ],
      "requestIDs": [
        "symphony_talent_careers_site_planning",
        "phenom_careers_site_planning",
        "radancy_careers_site_planning"
      ],
      "caveats": [
        "This comparative audit cites only the three local Company Brand Audit fixtures and their Browser Evidence request IDs.",
        "The fixture is not a live-web comparative audit and does not support market-current claims.",
        "Review-site, benefits, employee story, and career-mobility evidence are unavailable in this slice.",
        "The file is read-only provenance/source metadata, not a generated report or viewer payload.",
        "This company audit cites only one local Browser Evidence registry row.",
        "The fixture is not a live-web capture and does not support market-current claims.",
        "Review-site coverage is unavailable in this slice.",
        "Review platforms are required in the full workflow but are outside this first local fixture slice.",
        "This fixture does not claim the source URLs still contain the sampled positioning. This fixture contains local Browser Evidence Capture V0 pages, registry rows, and crop assets for provenance only; it does not contain live-web captures. This fixture is only evidence for Artifact Bundle preview, provenance, Work Record handoff behavior, and local browser evidence registry inspection."
      ]
    },
    {
      "theme": "Scale and reputation proof",
      "dimension": "Status",
      "companyScores": {
        "Symphony Talent": "Present",
        "Phenom": "Present",
        "Radancy": "Strong"
      },
      "fixtureImplication": "Radancy carries the strongest status signal through enterprise-scale positioning.",
      "sourceURLs": [
        "https://www.symphonytalent.com/",
        "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/symphony-talent-careers.html",
        "https://www.phenom.com/",
        "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/phenom-careers.html",
        "https://www.radancy.com/en/",
        "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/radancy-careers.html"
      ],
      "requestIDs": [
        "symphony_talent_careers_site_planning",
        "phenom_careers_site_planning",
        "radancy_careers_site_planning"
      ],
      "caveats": [
        "This comparative audit cites only the three local Company Brand Audit fixtures and their Browser Evidence request IDs.",
        "The fixture is not a live-web comparative audit and does not support market-current claims.",
        "Review-site, benefits, employee story, and career-mobility evidence are unavailable in this slice.",
        "The file is read-only provenance/source metadata, not a generated report or viewer payload.",
        "This company audit cites only one local Browser Evidence registry row.",
        "The fixture is not a live-web capture and does not support market-current claims.",
        "Review-site coverage is unavailable in this slice.",
        "Review platforms are required in the full workflow but are outside this first local fixture slice.",
        "This fixture does not claim the source URLs still contain the sampled positioning. This fixture contains local Browser Evidence Capture V0 pages, registry rows, and crop assets for provenance only; it does not contain live-web captures. This fixture is only evidence for Artifact Bundle preview, provenance, Work Record handoff behavior, and local browser evidence registry inspection."
      ]
    }
  ],
  "kilosPositioningMatrix": [
    {
      "dimension": "impact",
      "client_read": "Symphony Talent frames impact as helping employers reach candidates with more relevant talent experiences through craft, technology, and partnership.",
      "competitor_reads": [
        {
          "company": "Phenom",
          "read": "Phenom frames impact as making every talent moment more personal through intelligent product work and customer outcomes.",
          "company_audit_id": "company-brand-audit:phenom",
          "request_ids": [
            "phenom_careers_site_planning"
          ]
        },
        {
          "company": "Radancy",
          "read": "Radancy's local evidence is less impact-led and more focused on enterprise scale and expertise.",
          "company_audit_id": "company-brand-audit:radancy",
          "request_ids": [
            "radancy_careers_site_planning"
          ]
        }
      ],
      "synthesis": "Impact is a shared category, but Symphony Talent and Phenom carry clearer impact narratives in this fixture slice.",
      "company_audit_ids": [
        "company-brand-audit:symphony-talent",
        "company-brand-audit:phenom",
        "company-brand-audit:radancy"
      ],
      "request_ids": [
        "symphony_talent_careers_site_planning",
        "phenom_careers_site_planning",
        "radancy_careers_site_planning"
      ]
    },
    {
      "dimension": "opportunity",
      "client_read": "Symphony Talent signals opportunity through craft, recruitment marketing technology, and client partnership as expertise-building contexts.",
      "competitor_reads": [
        {
          "company": "Phenom",
          "read": "Phenom implies opportunity through builder culture and intelligent product work, but the fixture does not prove specific mobility paths.",
          "company_audit_id": "company-brand-audit:phenom",
          "request_ids": [
            "phenom_careers_site_planning"
          ]
        },
        {
          "company": "Radancy",
          "read": "Radancy signals opportunity through specialist recruitment marketing expertise and enterprise program exposure.",
          "company_audit_id": "company-brand-audit:radancy",
          "request_ids": [
            "radancy_careers_site_planning"
          ]
        }
      ],
      "synthesis": "Opportunity is present as expertise and exposure, but none of the local fixtures prove concrete career progression or internal mobility.",
      "company_audit_ids": [
        "company-brand-audit:symphony-talent",
        "company-brand-audit:phenom",
        "company-brand-audit:radancy"
      ],
      "request_ids": [
        "symphony_talent_careers_site_planning",
        "phenom_careers_site_planning",
        "radancy_careers_site_planning"
      ]
    },
    {
      "dimension": "kinship",
      "client_read": "Symphony Talent's local fixture is collaborative in tone but does not provide employee community, belonging, or voice proof.",
      "competitor_reads": [
        {
          "company": "Phenom",
          "read": "Phenom has the clearest kinship signal through collaborative problem solving across teams.",
          "company_audit_id": "company-brand-audit:phenom",
          "request_ids": [
            "phenom_careers_site_planning"
          ]
        },
        {
          "company": "Radancy",
          "read": "Radancy's local fixture does not foreground kinship beyond the implied professional community around specialist expertise.",
          "company_audit_id": "company-brand-audit:radancy",
          "request_ids": [
            "radancy_careers_site_planning"
          ]
        }
      ],
      "synthesis": "Kinship is the weakest comparative dimension in the local evidence, with Phenom holding the clearest available signal.",
      "company_audit_ids": [
        "company-brand-audit:symphony-talent",
        "company-brand-audit:phenom",
        "company-brand-audit:radancy"
      ],
      "request_ids": [
        "symphony_talent_careers_site_planning",
        "phenom_careers_site_planning",
        "radancy_careers_site_planning"
      ]
    },
    {
      "dimension": "status",
      "client_read": "Symphony Talent does not rely on reputation or scale proof in the local hero fixture.",
      "competitor_reads": [
        {
          "company": "Phenom",
          "read": "Phenom's local evidence is product-led rather than status-led.",
          "company_audit_id": "company-brand-audit:phenom",
          "request_ids": [
            "phenom_careers_site_planning"
          ]
        },
        {
          "company": "Radancy",
          "read": "Radancy owns the clearest status position through enterprise hiring programs, global reach, and established client work.",
          "company_audit_id": "company-brand-audit:radancy",
          "request_ids": [
            "radancy_careers_site_planning"
          ]
        }
      ],
      "synthesis": "Status is Radancy's strongest relative lane in this fixture set.",
      "company_audit_ids": [
        "company-brand-audit:symphony-talent",
        "company-brand-audit:phenom",
        "company-brand-audit:radancy"
      ],
      "request_ids": [
        "symphony_talent_careers_site_planning",
        "phenom_careers_site_planning",
        "radancy_careers_site_planning"
      ]
    },
    {
      "dimension": "lifestyle",
      "client_read": "Symphony Talent has no benefits, flexibility, work-life, or stability evidence in the local fixture.",
      "competitor_reads": [
        {
          "company": "Phenom",
          "read": "Phenom has no lifestyle evidence in the local fixture.",
          "company_audit_id": "company-brand-audit:phenom",
          "request_ids": []
        },
        {
          "company": "Radancy",
          "read": "Radancy has no lifestyle evidence in the local fixture.",
          "company_audit_id": "company-brand-audit:radancy",
          "request_ids": []
        }
      ],
      "synthesis": "Lifestyle is unavailable across the comparative fixture and should not be inferred from the current evidence.",
      "company_audit_ids": [
        "company-brand-audit:symphony-talent",
        "company-brand-audit:phenom",
        "company-brand-audit:radancy"
      ],
      "request_ids": []
    }
  ],
  "standoutEngagementExamples": [
    {
      "company": "Symphony Talent",
      "example": "Hero-level positioning connects employee craft and client partnership to candidate relevance.",
      "company_audit_ids": [
        "company-brand-audit:symphony-talent"
      ],
      "request_ids": [
        "symphony_talent_careers_site_planning"
      ]
    },
    {
      "company": "Phenom",
      "example": "Culture-card positioning turns personalization into a product-building employee story.",
      "company_audit_ids": [
        "company-brand-audit:phenom"
      ],
      "request_ids": [
        "phenom_careers_site_planning"
      ]
    },
    {
      "company": "Radancy",
      "example": "Proof-block positioning uses enterprise scale and specialist expertise as employer-brand proof.",
      "company_audit_ids": [
        "company-brand-audit:radancy"
      ],
      "request_ids": [
        "radancy_careers_site_planning"
      ]
    }
  ],
  "implicationsForClient": [
    {
      "implication": "Defend the craft-and-impact lane with sharper proof.",
      "summary": "Symphony Talent has a credible craft, technology, and client-partnership position in the fixture, but Phenom can outflank it on product energy and Radancy can outflank it on scale unless future evidence adds employee stories, outcome proof, and clearer career signals.",
      "company_audit_ids": [
        "company-brand-audit:symphony-talent",
        "company-brand-audit:phenom",
        "company-brand-audit:radancy"
      ],
      "request_ids": [
        "symphony_talent_careers_site_planning",
        "phenom_careers_site_planning",
        "radancy_careers_site_planning"
      ]
    },
    {
      "implication": "Treat lifestyle and review sentiment as unresolved evidence requirements.",
      "summary": "Because all three company audits mark review-site coverage as unavailable and omit benefits or flexibility proof, the comparative audit should not make employee sentiment or lifestyle recommendations beyond identifying the gap.",
      "company_audit_ids": [
        "company-brand-audit:symphony-talent",
        "company-brand-audit:phenom",
        "company-brand-audit:radancy"
      ],
      "request_ids": [
        "symphony_talent_careers_site_planning",
        "phenom_careers_site_planning",
        "radancy_careers_site_planning"
      ]
    }
  ],
  "evidenceBackedClaims": [
    {
      "id": "claim:comparative-shared-talent-experience-frame",
      "claim": "The three local company audit fixtures share a talent-experience employer-brand frame while emphasizing different proof centers.",
      "company_audit_ids": [
        "company-brand-audit:symphony-talent",
        "company-brand-audit:phenom",
        "company-brand-audit:radancy"
      ],
      "request_ids": [
        "symphony_talent_careers_site_planning",
        "phenom_careers_site_planning",
        "radancy_careers_site_planning"
      ]
    },
    {
      "id": "claim:comparative-symphony-craft-client-partnership",
      "claim": "Symphony Talent's local client fixture is most differentiated by the blend of craft, recruitment marketing technology, impact, and client partnership.",
      "company_audit_ids": [
        "company-brand-audit:symphony-talent"
      ],
      "request_ids": [
        "symphony_talent_careers_site_planning"
      ]
    },
    {
      "id": "claim:comparative-phenom-product-personalization",
      "claim": "Phenom's local competitor fixture is most differentiated by product-led personalization and builder culture.",
      "company_audit_ids": [
        "company-brand-audit:phenom"
      ],
      "request_ids": [
        "phenom_careers_site_planning"
      ]
    },
    {
      "id": "claim:comparative-radancy-enterprise-status",
      "claim": "Radancy's local competitor fixture is most differentiated by enterprise scale, global reach, and specialist recruitment marketing expertise.",
      "company_audit_ids": [
        "company-brand-audit:radancy"
      ],
      "request_ids": [
        "radancy_careers_site_planning"
      ]
    }
  ],
  "reviewSiteComparison": {
    "coverage_status": "unavailable",
    "summary": "No Glassdoor, Indeed, or other review-site evidence is present in any of the three local Company Brand Audit fixtures.",
    "company_audit_ids": [
      "company-brand-audit:symphony-talent",
      "company-brand-audit:phenom",
      "company-brand-audit:radancy"
    ],
    "request_ids": [],
    "caveat": "Review platforms are required in the full workflow but are outside this first local comparative fixture slice."
  },
  "provenance": {
    "created_at": "2026-05-07T16:30:00Z",
    "derived_from_company_audit_ids": [
      "company-brand-audit:symphony-talent",
      "company-brand-audit:phenom",
      "company-brand-audit:radancy"
    ],
    "derived_from_company_audit_paths": [
      "company-audits/symphony-talent.json",
      "company-audits/phenom.json",
      "company-audits/radancy.json"
    ],
    "derived_from_registry": "browser-evidence/registry.json",
    "browser_evidence_request_ids": [
      "symphony_talent_careers_site_planning",
      "phenom_careers_site_planning",
      "radancy_careers_site_planning"
    ],
    "local_fixture_evidence_only": true,
    "live_websites": false,
    "report_generation": false,
    "provenance_only": true,
    "read_only": true,
    "non_goals": [
      "live_collection",
      "report_generation",
      "export_execution",
      "viewer",
      "workflow_engine",
      "replay",
      "repair",
      "macro_playback"
    ]
  }
};

const introContent = {
  "auditPreamble": {
    "title": "Local fixture comparative audit",
    "introduction": "This report renders the checked-in Symphony Talent, Phenom, and Radancy Employer Brand comparative audit fixture. The claims are fixture claims grounded in local source metadata, company audit JSON, comparative KILOS synthesis, and Browser Evidence registry rows.",
    "methodologyTitle": "Fixture methodology",
    "methodology": "The payload is deterministically composed from existing repo files: project intake, public source metadata, local Browser Evidence registry entries, Company Brand Audit fixtures, Comparative Brand Audit fixtures, and the Markdown KILOS snapshot. It does not browse, collect live pages, infer current market state, run a workflow, or execute an export.",
    "methodologyFocusAreas": [
      "Company employer value proposition and KILOS analysis from the structured company audit JSON files.",
      "Comparative shared themes, differentiators, whitespace, and client implications from the Comparative Brand Audit fixture.",
      "Local Browser Evidence fixture pages and crop assets, preserving request IDs, source URLs, selectors, timestamps, and caveats."
    ],
    "closing": "Use this as a populated prototype fixture for report rendering and evidence handoff inspection, not as a current live-web employer brand audit.",
    "frameworkIntroduction": "KILOS is used here only as the fixture analysis lens across Kinship, Impact, Lifestyle, Opportunity, and Status.",
    "sourceURLs": [
      "https://www.symphonytalent.com/",
      "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/symphony-talent-careers.html",
      "https://www.phenom.com/",
      "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/phenom-careers.html",
      "https://www.radancy.com/en/",
      "../docs/design/fixtures/aos-artifacts/employer-brand-comparative-audit/browser-evidence/html/radancy-careers.html"
    ],
    "requestIDs": [
      "symphony_talent_careers_site_planning",
      "phenom_careers_site_planning",
      "radancy_careers_site_planning"
    ],
    "caveats": [
      "This comparative audit cites only the three local Company Brand Audit fixtures and their Browser Evidence request IDs.",
      "The fixture is not a live-web comparative audit and does not support market-current claims.",
      "Review-site, benefits, employee story, and career-mobility evidence are unavailable in this slice.",
      "The file is read-only provenance/source metadata, not a generated report or viewer payload.",
      "This company audit cites only one local Browser Evidence registry row.",
      "The fixture is not a live-web capture and does not support market-current claims.",
      "Review-site coverage is unavailable in this slice.",
      "Review platforms are required in the full workflow but are outside this first local fixture slice.",
      "This fixture does not claim the source URLs still contain the sampled positioning. This fixture contains local Browser Evidence Capture V0 pages, registry rows, and crop assets for provenance only; it does not contain live-web captures. This fixture is only evidence for Artifact Bundle preview, provenance, Work Record handoff behavior, and local browser evidence registry inspection."
    ]
  }
};
